---
version: "3.9"

services:
  laravel:
    image: ghcr.io/pvledoux/wesh_php_fpm_prod:latest
    networks:
      - traefik-public
      - wesh
    configs:
      - source: wesh_environment
        target: /var/www/html/.env
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=traefik-public"
        - "traefik.http.routers.wesh.service=wesh"
        - "traefik.http.routers.wesh.rule=Host(`wesh.tools.iad-arts.be`)"
        - "traefik.http.routers.wesh.entrypoints=websecure"
        - "traefik.http.services.wesh.loadbalancer.server.port=8000"
        - "traefik.http.routers.wesh.tls.certresolver=production"
        - "traefik.http.routers.wesh.tls=true"

networks:
  wesh:
    driver: overlay
    attachable: true
  traefik-public:
    external: true

configs:
  wesh_environment:
    external: true
